// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: entity_metadata-entity.proto

package mpi.aida.access.compiledprotos;

public final class EntityMetadataEntity {
  private EntityMetadataEntity() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface KeyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Key)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 entity = 1;</code>
     */
    boolean hasEntity();
    /**
     * <code>required int32 entity = 1;</code>
     */
    int getEntity();
  }
  /**
   * Protobuf type {@code Key}
   */
  public static final class Key extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Key)
      KeyOrBuilder {
    // Use Key.newBuilder() to construct.
    private Key(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Key(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Key defaultInstance;
    public static Key getDefaultInstance() {
      return defaultInstance;
    }

    public Key getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Key(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              entity_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return mpi.aida.access.compiledprotos.EntityMetadataEntity.internal_static_Key_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return mpi.aida.access.compiledprotos.EntityMetadataEntity.internal_static_Key_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              mpi.aida.access.compiledprotos.EntityMetadataEntity.Key.class, mpi.aida.access.compiledprotos.EntityMetadataEntity.Key.Builder.class);
    }

    public static com.google.protobuf.Parser<Key> PARSER =
        new com.google.protobuf.AbstractParser<Key>() {
      public Key parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Key(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Key> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ENTITY_FIELD_NUMBER = 1;
    private int entity_;
    /**
     * <code>required int32 entity = 1;</code>
     */
    public boolean hasEntity() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 entity = 1;</code>
     */
    public int getEntity() {
      return entity_;
    }

    private void initFields() {
      entity_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasEntity()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, entity_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, entity_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static mpi.aida.access.compiledprotos.EntityMetadataEntity.Key parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mpi.aida.access.compiledprotos.EntityMetadataEntity.Key parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mpi.aida.access.compiledprotos.EntityMetadataEntity.Key parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mpi.aida.access.compiledprotos.EntityMetadataEntity.Key parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mpi.aida.access.compiledprotos.EntityMetadataEntity.Key parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static mpi.aida.access.compiledprotos.EntityMetadataEntity.Key parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static mpi.aida.access.compiledprotos.EntityMetadataEntity.Key parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static mpi.aida.access.compiledprotos.EntityMetadataEntity.Key parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static mpi.aida.access.compiledprotos.EntityMetadataEntity.Key parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static mpi.aida.access.compiledprotos.EntityMetadataEntity.Key parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(mpi.aida.access.compiledprotos.EntityMetadataEntity.Key prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Key}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Key)
        mpi.aida.access.compiledprotos.EntityMetadataEntity.KeyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return mpi.aida.access.compiledprotos.EntityMetadataEntity.internal_static_Key_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return mpi.aida.access.compiledprotos.EntityMetadataEntity.internal_static_Key_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                mpi.aida.access.compiledprotos.EntityMetadataEntity.Key.class, mpi.aida.access.compiledprotos.EntityMetadataEntity.Key.Builder.class);
      }

      // Construct using mpi.aida.access.compiledprotos.EntityMetadataEntity.Key.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        entity_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return mpi.aida.access.compiledprotos.EntityMetadataEntity.internal_static_Key_descriptor;
      }

      public mpi.aida.access.compiledprotos.EntityMetadataEntity.Key getDefaultInstanceForType() {
        return mpi.aida.access.compiledprotos.EntityMetadataEntity.Key.getDefaultInstance();
      }

      public mpi.aida.access.compiledprotos.EntityMetadataEntity.Key build() {
        mpi.aida.access.compiledprotos.EntityMetadataEntity.Key result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public mpi.aida.access.compiledprotos.EntityMetadataEntity.Key buildPartial() {
        mpi.aida.access.compiledprotos.EntityMetadataEntity.Key result = new mpi.aida.access.compiledprotos.EntityMetadataEntity.Key(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.entity_ = entity_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof mpi.aida.access.compiledprotos.EntityMetadataEntity.Key) {
          return mergeFrom((mpi.aida.access.compiledprotos.EntityMetadataEntity.Key)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(mpi.aida.access.compiledprotos.EntityMetadataEntity.Key other) {
        if (other == mpi.aida.access.compiledprotos.EntityMetadataEntity.Key.getDefaultInstance()) return this;
        if (other.hasEntity()) {
          setEntity(other.getEntity());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasEntity()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        mpi.aida.access.compiledprotos.EntityMetadataEntity.Key parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (mpi.aida.access.compiledprotos.EntityMetadataEntity.Key) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int entity_ ;
      /**
       * <code>required int32 entity = 1;</code>
       */
      public boolean hasEntity() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 entity = 1;</code>
       */
      public int getEntity() {
        return entity_;
      }
      /**
       * <code>required int32 entity = 1;</code>
       */
      public Builder setEntity(int value) {
        bitField0_ |= 0x00000001;
        entity_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 entity = 1;</code>
       */
      public Builder clearEntity() {
        bitField0_ = (bitField0_ & ~0x00000001);
        entity_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Key)
    }

    static {
      defaultInstance = new Key(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Key)
  }

  public interface ValuesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Values)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Values.Value values = 1;</code>
     */
    java.util.List<mpi.aida.access.compiledprotos.EntityMetadataEntity.Values.Value> 
        getValuesList();
    /**
     * <code>repeated .Values.Value values = 1;</code>
     */
    mpi.aida.access.compiledprotos.EntityMetadataEntity.Values.Value getValues(int index);
    /**
     * <code>repeated .Values.Value values = 1;</code>
     */
    int getValuesCount();
    /**
     * <code>repeated .Values.Value values = 1;</code>
     */
    java.util.List<? extends mpi.aida.access.compiledprotos.EntityMetadataEntity.Values.ValueOrBuilder> 
        getValuesOrBuilderList();
    /**
     * <code>repeated .Values.Value values = 1;</code>
     */
    mpi.aida.access.compiledprotos.EntityMetadataEntity.Values.ValueOrBuilder getValuesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Values}
   */
  public static final class Values extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Values)
      ValuesOrBuilder {
    // Use Values.newBuilder() to construct.
    private Values(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Values(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Values defaultInstance;
    public static Values getDefaultInstance() {
      return defaultInstance;
    }

    public Values getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Values(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                values_ = new java.util.ArrayList<mpi.aida.access.compiledprotos.EntityMetadataEntity.Values.Value>();
                mutable_bitField0_ |= 0x00000001;
              }
              values_.add(input.readMessage(mpi.aida.access.compiledprotos.EntityMetadataEntity.Values.Value.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          values_ = java.util.Collections.unmodifiableList(values_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return mpi.aida.access.compiledprotos.EntityMetadataEntity.internal_static_Values_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return mpi.aida.access.compiledprotos.EntityMetadataEntity.internal_static_Values_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              mpi.aida.access.compiledprotos.EntityMetadataEntity.Values.class, mpi.aida.access.compiledprotos.EntityMetadataEntity.Values.Builder.class);
    }

    public static com.google.protobuf.Parser<Values> PARSER =
        new com.google.protobuf.AbstractParser<Values>() {
      public Values parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Values(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Values> getParserForType() {
      return PARSER;
    }

    public interface ValueOrBuilder extends
        // @@protoc_insertion_point(interface_extends:Values.Value)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required string humanreadablererpresentation = 2;</code>
       */
      boolean hasHumanreadablererpresentation();
      /**
       * <code>required string humanreadablererpresentation = 2;</code>
       */
      java.lang.String getHumanreadablererpresentation();
      /**
       * <code>required string humanreadablererpresentation = 2;</code>
       */
      com.google.protobuf.ByteString
          getHumanreadablererpresentationBytes();

      /**
       * <code>required string url = 3;</code>
       */
      boolean hasUrl();
      /**
       * <code>required string url = 3;</code>
       */
      java.lang.String getUrl();
      /**
       * <code>required string url = 3;</code>
       */
      com.google.protobuf.ByteString
          getUrlBytes();

      /**
       * <code>required string knowledgebase = 4;</code>
       */
      boolean hasKnowledgebase();
      /**
       * <code>required string knowledgebase = 4;</code>
       */
      java.lang.String getKnowledgebase();
      /**
       * <code>required string knowledgebase = 4;</code>
       */
      com.google.protobuf.ByteString
          getKnowledgebaseBytes();

      /**
       * <code>optional string depictionurl = 5;</code>
       */
      boolean hasDepictionurl();
      /**
       * <code>optional string depictionurl = 5;</code>
       */
      java.lang.String getDepictionurl();
      /**
       * <code>optional string depictionurl = 5;</code>
       */
      com.google.protobuf.ByteString
          getDepictionurlBytes();

      /**
       * <code>optional string description = 6;</code>
       */
      boolean hasDescription();
      /**
       * <code>optional string description = 6;</code>
       */
      java.lang.String getDescription();
      /**
       * <code>optional string description = 6;</code>
       */
      com.google.protobuf.ByteString
          getDescriptionBytes();
    }
    /**
     * Protobuf type {@code Values.Value}
     */
    public static final class Value extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:Values.Value)
        ValueOrBuilder {
      // Use Value.newBuilder() to construct.
      private Value(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Value(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Value defaultInstance;
      public static Value getDefaultInstance() {
        return defaultInstance;
      }

      public Value getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Value(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 18: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000001;
                humanreadablererpresentation_ = bs;
                break;
              }
              case 26: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000002;
                url_ = bs;
                break;
              }
              case 34: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000004;
                knowledgebase_ = bs;
                break;
              }
              case 42: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000008;
                depictionurl_ = bs;
                break;
              }
              case 50: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000010;
                description_ = bs;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return mpi.aida.access.compiledprotos.EntityMetadataEntity.internal_static_Values_Value_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return mpi.aida.access.compiledprotos.EntityMetadataEntity.internal_static_Values_Value_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                mpi.aida.access.compiledprotos.EntityMetadataEntity.Values.Value.class, mpi.aida.access.compiledprotos.EntityMetadataEntity.Values.Value.Builder.class);
      }

      public static com.google.protobuf.Parser<Value> PARSER =
          new com.google.protobuf.AbstractParser<Value>() {
        public Value parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Value(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<Value> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      public static final int HUMANREADABLERERPRESENTATION_FIELD_NUMBER = 2;
      private java.lang.Object humanreadablererpresentation_;
      /**
       * <code>required string humanreadablererpresentation = 2;</code>
       */
      public boolean hasHumanreadablererpresentation() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string humanreadablererpresentation = 2;</code>
       */
      public java.lang.String getHumanreadablererpresentation() {
        java.lang.Object ref = humanreadablererpresentation_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            humanreadablererpresentation_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string humanreadablererpresentation = 2;</code>
       */
      public com.google.protobuf.ByteString
          getHumanreadablererpresentationBytes() {
        java.lang.Object ref = humanreadablererpresentation_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          humanreadablererpresentation_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int URL_FIELD_NUMBER = 3;
      private java.lang.Object url_;
      /**
       * <code>required string url = 3;</code>
       */
      public boolean hasUrl() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string url = 3;</code>
       */
      public java.lang.String getUrl() {
        java.lang.Object ref = url_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            url_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string url = 3;</code>
       */
      public com.google.protobuf.ByteString
          getUrlBytes() {
        java.lang.Object ref = url_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          url_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int KNOWLEDGEBASE_FIELD_NUMBER = 4;
      private java.lang.Object knowledgebase_;
      /**
       * <code>required string knowledgebase = 4;</code>
       */
      public boolean hasKnowledgebase() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string knowledgebase = 4;</code>
       */
      public java.lang.String getKnowledgebase() {
        java.lang.Object ref = knowledgebase_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            knowledgebase_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string knowledgebase = 4;</code>
       */
      public com.google.protobuf.ByteString
          getKnowledgebaseBytes() {
        java.lang.Object ref = knowledgebase_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          knowledgebase_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int DEPICTIONURL_FIELD_NUMBER = 5;
      private java.lang.Object depictionurl_;
      /**
       * <code>optional string depictionurl = 5;</code>
       */
      public boolean hasDepictionurl() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string depictionurl = 5;</code>
       */
      public java.lang.String getDepictionurl() {
        java.lang.Object ref = depictionurl_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            depictionurl_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string depictionurl = 5;</code>
       */
      public com.google.protobuf.ByteString
          getDepictionurlBytes() {
        java.lang.Object ref = depictionurl_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          depictionurl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int DESCRIPTION_FIELD_NUMBER = 6;
      private java.lang.Object description_;
      /**
       * <code>optional string description = 6;</code>
       */
      public boolean hasDescription() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string description = 6;</code>
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            description_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string description = 6;</code>
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private void initFields() {
        humanreadablererpresentation_ = "";
        url_ = "";
        knowledgebase_ = "";
        depictionurl_ = "";
        description_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasHumanreadablererpresentation()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasUrl()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasKnowledgebase()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(2, getHumanreadablererpresentationBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(3, getUrlBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeBytes(4, getKnowledgebaseBytes());
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          output.writeBytes(5, getDepictionurlBytes());
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          output.writeBytes(6, getDescriptionBytes());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getHumanreadablererpresentationBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(3, getUrlBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(4, getKnowledgebaseBytes());
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(5, getDepictionurlBytes());
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(6, getDescriptionBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static mpi.aida.access.compiledprotos.EntityMetadataEntity.Values.Value parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static mpi.aida.access.compiledprotos.EntityMetadataEntity.Values.Value parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static mpi.aida.access.compiledprotos.EntityMetadataEntity.Values.Value parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static mpi.aida.access.compiledprotos.EntityMetadataEntity.Values.Value parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static mpi.aida.access.compiledprotos.EntityMetadataEntity.Values.Value parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static mpi.aida.access.compiledprotos.EntityMetadataEntity.Values.Value parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static mpi.aida.access.compiledprotos.EntityMetadataEntity.Values.Value parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static mpi.aida.access.compiledprotos.EntityMetadataEntity.Values.Value parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static mpi.aida.access.compiledprotos.EntityMetadataEntity.Values.Value parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static mpi.aida.access.compiledprotos.EntityMetadataEntity.Values.Value parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(mpi.aida.access.compiledprotos.EntityMetadataEntity.Values.Value prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code Values.Value}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:Values.Value)
          mpi.aida.access.compiledprotos.EntityMetadataEntity.Values.ValueOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return mpi.aida.access.compiledprotos.EntityMetadataEntity.internal_static_Values_Value_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return mpi.aida.access.compiledprotos.EntityMetadataEntity.internal_static_Values_Value_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  mpi.aida.access.compiledprotos.EntityMetadataEntity.Values.Value.class, mpi.aida.access.compiledprotos.EntityMetadataEntity.Values.Value.Builder.class);
        }

        // Construct using mpi.aida.access.compiledprotos.EntityMetadataEntity.Values.Value.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          humanreadablererpresentation_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          url_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          knowledgebase_ = "";
          bitField0_ = (bitField0_ & ~0x00000004);
          depictionurl_ = "";
          bitField0_ = (bitField0_ & ~0x00000008);
          description_ = "";
          bitField0_ = (bitField0_ & ~0x00000010);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return mpi.aida.access.compiledprotos.EntityMetadataEntity.internal_static_Values_Value_descriptor;
        }

        public mpi.aida.access.compiledprotos.EntityMetadataEntity.Values.Value getDefaultInstanceForType() {
          return mpi.aida.access.compiledprotos.EntityMetadataEntity.Values.Value.getDefaultInstance();
        }

        public mpi.aida.access.compiledprotos.EntityMetadataEntity.Values.Value build() {
          mpi.aida.access.compiledprotos.EntityMetadataEntity.Values.Value result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public mpi.aida.access.compiledprotos.EntityMetadataEntity.Values.Value buildPartial() {
          mpi.aida.access.compiledprotos.EntityMetadataEntity.Values.Value result = new mpi.aida.access.compiledprotos.EntityMetadataEntity.Values.Value(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.humanreadablererpresentation_ = humanreadablererpresentation_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.url_ = url_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.knowledgebase_ = knowledgebase_;
          if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
            to_bitField0_ |= 0x00000008;
          }
          result.depictionurl_ = depictionurl_;
          if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
            to_bitField0_ |= 0x00000010;
          }
          result.description_ = description_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof mpi.aida.access.compiledprotos.EntityMetadataEntity.Values.Value) {
            return mergeFrom((mpi.aida.access.compiledprotos.EntityMetadataEntity.Values.Value)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(mpi.aida.access.compiledprotos.EntityMetadataEntity.Values.Value other) {
          if (other == mpi.aida.access.compiledprotos.EntityMetadataEntity.Values.Value.getDefaultInstance()) return this;
          if (other.hasHumanreadablererpresentation()) {
            bitField0_ |= 0x00000001;
            humanreadablererpresentation_ = other.humanreadablererpresentation_;
            onChanged();
          }
          if (other.hasUrl()) {
            bitField0_ |= 0x00000002;
            url_ = other.url_;
            onChanged();
          }
          if (other.hasKnowledgebase()) {
            bitField0_ |= 0x00000004;
            knowledgebase_ = other.knowledgebase_;
            onChanged();
          }
          if (other.hasDepictionurl()) {
            bitField0_ |= 0x00000008;
            depictionurl_ = other.depictionurl_;
            onChanged();
          }
          if (other.hasDescription()) {
            bitField0_ |= 0x00000010;
            description_ = other.description_;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasHumanreadablererpresentation()) {
            
            return false;
          }
          if (!hasUrl()) {
            
            return false;
          }
          if (!hasKnowledgebase()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          mpi.aida.access.compiledprotos.EntityMetadataEntity.Values.Value parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (mpi.aida.access.compiledprotos.EntityMetadataEntity.Values.Value) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private java.lang.Object humanreadablererpresentation_ = "";
        /**
         * <code>required string humanreadablererpresentation = 2;</code>
         */
        public boolean hasHumanreadablererpresentation() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string humanreadablererpresentation = 2;</code>
         */
        public java.lang.String getHumanreadablererpresentation() {
          java.lang.Object ref = humanreadablererpresentation_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              humanreadablererpresentation_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string humanreadablererpresentation = 2;</code>
         */
        public com.google.protobuf.ByteString
            getHumanreadablererpresentationBytes() {
          java.lang.Object ref = humanreadablererpresentation_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            humanreadablererpresentation_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string humanreadablererpresentation = 2;</code>
         */
        public Builder setHumanreadablererpresentation(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          humanreadablererpresentation_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string humanreadablererpresentation = 2;</code>
         */
        public Builder clearHumanreadablererpresentation() {
          bitField0_ = (bitField0_ & ~0x00000001);
          humanreadablererpresentation_ = getDefaultInstance().getHumanreadablererpresentation();
          onChanged();
          return this;
        }
        /**
         * <code>required string humanreadablererpresentation = 2;</code>
         */
        public Builder setHumanreadablererpresentationBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          humanreadablererpresentation_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object url_ = "";
        /**
         * <code>required string url = 3;</code>
         */
        public boolean hasUrl() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required string url = 3;</code>
         */
        public java.lang.String getUrl() {
          java.lang.Object ref = url_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              url_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string url = 3;</code>
         */
        public com.google.protobuf.ByteString
            getUrlBytes() {
          java.lang.Object ref = url_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            url_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string url = 3;</code>
         */
        public Builder setUrl(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          url_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string url = 3;</code>
         */
        public Builder clearUrl() {
          bitField0_ = (bitField0_ & ~0x00000002);
          url_ = getDefaultInstance().getUrl();
          onChanged();
          return this;
        }
        /**
         * <code>required string url = 3;</code>
         */
        public Builder setUrlBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          url_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object knowledgebase_ = "";
        /**
         * <code>required string knowledgebase = 4;</code>
         */
        public boolean hasKnowledgebase() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>required string knowledgebase = 4;</code>
         */
        public java.lang.String getKnowledgebase() {
          java.lang.Object ref = knowledgebase_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              knowledgebase_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string knowledgebase = 4;</code>
         */
        public com.google.protobuf.ByteString
            getKnowledgebaseBytes() {
          java.lang.Object ref = knowledgebase_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            knowledgebase_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string knowledgebase = 4;</code>
         */
        public Builder setKnowledgebase(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          knowledgebase_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string knowledgebase = 4;</code>
         */
        public Builder clearKnowledgebase() {
          bitField0_ = (bitField0_ & ~0x00000004);
          knowledgebase_ = getDefaultInstance().getKnowledgebase();
          onChanged();
          return this;
        }
        /**
         * <code>required string knowledgebase = 4;</code>
         */
        public Builder setKnowledgebaseBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          knowledgebase_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object depictionurl_ = "";
        /**
         * <code>optional string depictionurl = 5;</code>
         */
        public boolean hasDepictionurl() {
          return ((bitField0_ & 0x00000008) == 0x00000008);
        }
        /**
         * <code>optional string depictionurl = 5;</code>
         */
        public java.lang.String getDepictionurl() {
          java.lang.Object ref = depictionurl_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              depictionurl_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string depictionurl = 5;</code>
         */
        public com.google.protobuf.ByteString
            getDepictionurlBytes() {
          java.lang.Object ref = depictionurl_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            depictionurl_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string depictionurl = 5;</code>
         */
        public Builder setDepictionurl(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
          depictionurl_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string depictionurl = 5;</code>
         */
        public Builder clearDepictionurl() {
          bitField0_ = (bitField0_ & ~0x00000008);
          depictionurl_ = getDefaultInstance().getDepictionurl();
          onChanged();
          return this;
        }
        /**
         * <code>optional string depictionurl = 5;</code>
         */
        public Builder setDepictionurlBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
          depictionurl_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object description_ = "";
        /**
         * <code>optional string description = 6;</code>
         */
        public boolean hasDescription() {
          return ((bitField0_ & 0x00000010) == 0x00000010);
        }
        /**
         * <code>optional string description = 6;</code>
         */
        public java.lang.String getDescription() {
          java.lang.Object ref = description_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              description_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string description = 6;</code>
         */
        public com.google.protobuf.ByteString
            getDescriptionBytes() {
          java.lang.Object ref = description_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            description_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string description = 6;</code>
         */
        public Builder setDescription(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
          description_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string description = 6;</code>
         */
        public Builder clearDescription() {
          bitField0_ = (bitField0_ & ~0x00000010);
          description_ = getDefaultInstance().getDescription();
          onChanged();
          return this;
        }
        /**
         * <code>optional string description = 6;</code>
         */
        public Builder setDescriptionBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
          description_ = value;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:Values.Value)
      }

      static {
        defaultInstance = new Value(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:Values.Value)
    }

    public static final int VALUES_FIELD_NUMBER = 1;
    private java.util.List<mpi.aida.access.compiledprotos.EntityMetadataEntity.Values.Value> values_;
    /**
     * <code>repeated .Values.Value values = 1;</code>
     */
    public java.util.List<mpi.aida.access.compiledprotos.EntityMetadataEntity.Values.Value> getValuesList() {
      return values_;
    }
    /**
     * <code>repeated .Values.Value values = 1;</code>
     */
    public java.util.List<? extends mpi.aida.access.compiledprotos.EntityMetadataEntity.Values.ValueOrBuilder> 
        getValuesOrBuilderList() {
      return values_;
    }
    /**
     * <code>repeated .Values.Value values = 1;</code>
     */
    public int getValuesCount() {
      return values_.size();
    }
    /**
     * <code>repeated .Values.Value values = 1;</code>
     */
    public mpi.aida.access.compiledprotos.EntityMetadataEntity.Values.Value getValues(int index) {
      return values_.get(index);
    }
    /**
     * <code>repeated .Values.Value values = 1;</code>
     */
    public mpi.aida.access.compiledprotos.EntityMetadataEntity.Values.ValueOrBuilder getValuesOrBuilder(
        int index) {
      return values_.get(index);
    }

    private void initFields() {
      values_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getValuesCount(); i++) {
        if (!getValues(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < values_.size(); i++) {
        output.writeMessage(1, values_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < values_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, values_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static mpi.aida.access.compiledprotos.EntityMetadataEntity.Values parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mpi.aida.access.compiledprotos.EntityMetadataEntity.Values parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mpi.aida.access.compiledprotos.EntityMetadataEntity.Values parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mpi.aida.access.compiledprotos.EntityMetadataEntity.Values parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mpi.aida.access.compiledprotos.EntityMetadataEntity.Values parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static mpi.aida.access.compiledprotos.EntityMetadataEntity.Values parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static mpi.aida.access.compiledprotos.EntityMetadataEntity.Values parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static mpi.aida.access.compiledprotos.EntityMetadataEntity.Values parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static mpi.aida.access.compiledprotos.EntityMetadataEntity.Values parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static mpi.aida.access.compiledprotos.EntityMetadataEntity.Values parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(mpi.aida.access.compiledprotos.EntityMetadataEntity.Values prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Values}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Values)
        mpi.aida.access.compiledprotos.EntityMetadataEntity.ValuesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return mpi.aida.access.compiledprotos.EntityMetadataEntity.internal_static_Values_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return mpi.aida.access.compiledprotos.EntityMetadataEntity.internal_static_Values_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                mpi.aida.access.compiledprotos.EntityMetadataEntity.Values.class, mpi.aida.access.compiledprotos.EntityMetadataEntity.Values.Builder.class);
      }

      // Construct using mpi.aida.access.compiledprotos.EntityMetadataEntity.Values.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getValuesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (valuesBuilder_ == null) {
          values_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          valuesBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return mpi.aida.access.compiledprotos.EntityMetadataEntity.internal_static_Values_descriptor;
      }

      public mpi.aida.access.compiledprotos.EntityMetadataEntity.Values getDefaultInstanceForType() {
        return mpi.aida.access.compiledprotos.EntityMetadataEntity.Values.getDefaultInstance();
      }

      public mpi.aida.access.compiledprotos.EntityMetadataEntity.Values build() {
        mpi.aida.access.compiledprotos.EntityMetadataEntity.Values result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public mpi.aida.access.compiledprotos.EntityMetadataEntity.Values buildPartial() {
        mpi.aida.access.compiledprotos.EntityMetadataEntity.Values result = new mpi.aida.access.compiledprotos.EntityMetadataEntity.Values(this);
        int from_bitField0_ = bitField0_;
        if (valuesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            values_ = java.util.Collections.unmodifiableList(values_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.values_ = values_;
        } else {
          result.values_ = valuesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof mpi.aida.access.compiledprotos.EntityMetadataEntity.Values) {
          return mergeFrom((mpi.aida.access.compiledprotos.EntityMetadataEntity.Values)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(mpi.aida.access.compiledprotos.EntityMetadataEntity.Values other) {
        if (other == mpi.aida.access.compiledprotos.EntityMetadataEntity.Values.getDefaultInstance()) return this;
        if (valuesBuilder_ == null) {
          if (!other.values_.isEmpty()) {
            if (values_.isEmpty()) {
              values_ = other.values_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureValuesIsMutable();
              values_.addAll(other.values_);
            }
            onChanged();
          }
        } else {
          if (!other.values_.isEmpty()) {
            if (valuesBuilder_.isEmpty()) {
              valuesBuilder_.dispose();
              valuesBuilder_ = null;
              values_ = other.values_;
              bitField0_ = (bitField0_ & ~0x00000001);
              valuesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getValuesFieldBuilder() : null;
            } else {
              valuesBuilder_.addAllMessages(other.values_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getValuesCount(); i++) {
          if (!getValues(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        mpi.aida.access.compiledprotos.EntityMetadataEntity.Values parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (mpi.aida.access.compiledprotos.EntityMetadataEntity.Values) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<mpi.aida.access.compiledprotos.EntityMetadataEntity.Values.Value> values_ =
        java.util.Collections.emptyList();
      private void ensureValuesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          values_ = new java.util.ArrayList<mpi.aida.access.compiledprotos.EntityMetadataEntity.Values.Value>(values_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          mpi.aida.access.compiledprotos.EntityMetadataEntity.Values.Value, mpi.aida.access.compiledprotos.EntityMetadataEntity.Values.Value.Builder, mpi.aida.access.compiledprotos.EntityMetadataEntity.Values.ValueOrBuilder> valuesBuilder_;

      /**
       * <code>repeated .Values.Value values = 1;</code>
       */
      public java.util.List<mpi.aida.access.compiledprotos.EntityMetadataEntity.Values.Value> getValuesList() {
        if (valuesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(values_);
        } else {
          return valuesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Values.Value values = 1;</code>
       */
      public int getValuesCount() {
        if (valuesBuilder_ == null) {
          return values_.size();
        } else {
          return valuesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Values.Value values = 1;</code>
       */
      public mpi.aida.access.compiledprotos.EntityMetadataEntity.Values.Value getValues(int index) {
        if (valuesBuilder_ == null) {
          return values_.get(index);
        } else {
          return valuesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Values.Value values = 1;</code>
       */
      public Builder setValues(
          int index, mpi.aida.access.compiledprotos.EntityMetadataEntity.Values.Value value) {
        if (valuesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureValuesIsMutable();
          values_.set(index, value);
          onChanged();
        } else {
          valuesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Values.Value values = 1;</code>
       */
      public Builder setValues(
          int index, mpi.aida.access.compiledprotos.EntityMetadataEntity.Values.Value.Builder builderForValue) {
        if (valuesBuilder_ == null) {
          ensureValuesIsMutable();
          values_.set(index, builderForValue.build());
          onChanged();
        } else {
          valuesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Values.Value values = 1;</code>
       */
      public Builder addValues(mpi.aida.access.compiledprotos.EntityMetadataEntity.Values.Value value) {
        if (valuesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureValuesIsMutable();
          values_.add(value);
          onChanged();
        } else {
          valuesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Values.Value values = 1;</code>
       */
      public Builder addValues(
          int index, mpi.aida.access.compiledprotos.EntityMetadataEntity.Values.Value value) {
        if (valuesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureValuesIsMutable();
          values_.add(index, value);
          onChanged();
        } else {
          valuesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Values.Value values = 1;</code>
       */
      public Builder addValues(
          mpi.aida.access.compiledprotos.EntityMetadataEntity.Values.Value.Builder builderForValue) {
        if (valuesBuilder_ == null) {
          ensureValuesIsMutable();
          values_.add(builderForValue.build());
          onChanged();
        } else {
          valuesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Values.Value values = 1;</code>
       */
      public Builder addValues(
          int index, mpi.aida.access.compiledprotos.EntityMetadataEntity.Values.Value.Builder builderForValue) {
        if (valuesBuilder_ == null) {
          ensureValuesIsMutable();
          values_.add(index, builderForValue.build());
          onChanged();
        } else {
          valuesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Values.Value values = 1;</code>
       */
      public Builder addAllValues(
          java.lang.Iterable<? extends mpi.aida.access.compiledprotos.EntityMetadataEntity.Values.Value> values) {
        if (valuesBuilder_ == null) {
          ensureValuesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, values_);
          onChanged();
        } else {
          valuesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Values.Value values = 1;</code>
       */
      public Builder clearValues() {
        if (valuesBuilder_ == null) {
          values_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          valuesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Values.Value values = 1;</code>
       */
      public Builder removeValues(int index) {
        if (valuesBuilder_ == null) {
          ensureValuesIsMutable();
          values_.remove(index);
          onChanged();
        } else {
          valuesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Values.Value values = 1;</code>
       */
      public mpi.aida.access.compiledprotos.EntityMetadataEntity.Values.Value.Builder getValuesBuilder(
          int index) {
        return getValuesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Values.Value values = 1;</code>
       */
      public mpi.aida.access.compiledprotos.EntityMetadataEntity.Values.ValueOrBuilder getValuesOrBuilder(
          int index) {
        if (valuesBuilder_ == null) {
          return values_.get(index);  } else {
          return valuesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Values.Value values = 1;</code>
       */
      public java.util.List<? extends mpi.aida.access.compiledprotos.EntityMetadataEntity.Values.ValueOrBuilder> 
           getValuesOrBuilderList() {
        if (valuesBuilder_ != null) {
          return valuesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(values_);
        }
      }
      /**
       * <code>repeated .Values.Value values = 1;</code>
       */
      public mpi.aida.access.compiledprotos.EntityMetadataEntity.Values.Value.Builder addValuesBuilder() {
        return getValuesFieldBuilder().addBuilder(
            mpi.aida.access.compiledprotos.EntityMetadataEntity.Values.Value.getDefaultInstance());
      }
      /**
       * <code>repeated .Values.Value values = 1;</code>
       */
      public mpi.aida.access.compiledprotos.EntityMetadataEntity.Values.Value.Builder addValuesBuilder(
          int index) {
        return getValuesFieldBuilder().addBuilder(
            index, mpi.aida.access.compiledprotos.EntityMetadataEntity.Values.Value.getDefaultInstance());
      }
      /**
       * <code>repeated .Values.Value values = 1;</code>
       */
      public java.util.List<mpi.aida.access.compiledprotos.EntityMetadataEntity.Values.Value.Builder> 
           getValuesBuilderList() {
        return getValuesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          mpi.aida.access.compiledprotos.EntityMetadataEntity.Values.Value, mpi.aida.access.compiledprotos.EntityMetadataEntity.Values.Value.Builder, mpi.aida.access.compiledprotos.EntityMetadataEntity.Values.ValueOrBuilder> 
          getValuesFieldBuilder() {
        if (valuesBuilder_ == null) {
          valuesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              mpi.aida.access.compiledprotos.EntityMetadataEntity.Values.Value, mpi.aida.access.compiledprotos.EntityMetadataEntity.Values.Value.Builder, mpi.aida.access.compiledprotos.EntityMetadataEntity.Values.ValueOrBuilder>(
                  values_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          values_ = null;
        }
        return valuesBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:Values)
    }

    static {
      defaultInstance = new Values(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Values)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Key_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Key_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Values_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Values_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Values_Value_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Values_Value_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034entity_metadata-entity.proto\"\025\n\003Key\022\016\n" +
      "\006entity\030\001 \002(\005\"\245\001\n\006Values\022\035\n\006values\030\001 \003(\013" +
      "2\r.Values.Value\032|\n\005Value\022$\n\034humanreadabl" +
      "ererpresentation\030\002 \002(\t\022\013\n\003url\030\003 \002(\t\022\025\n\rk" +
      "nowledgebase\030\004 \002(\t\022\024\n\014depictionurl\030\005 \001(\t" +
      "\022\023\n\013description\030\006 \001(\tB \n\036mpi.aida.access" +
      ".compiledprotos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Key_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Key_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Key_descriptor,
        new java.lang.String[] { "Entity", });
    internal_static_Values_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Values_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Values_descriptor,
        new java.lang.String[] { "Values", });
    internal_static_Values_Value_descriptor =
      internal_static_Values_descriptor.getNestedTypes().get(0);
    internal_static_Values_Value_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Values_Value_descriptor,
        new java.lang.String[] { "Humanreadablererpresentation", "Url", "Knowledgebase", "Depictionurl", "Description", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
