// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: keyphrase_sources-source_id.proto

package mpi.aida.access.compiledprotos;

public final class KeyphraseSourcesSourceId {
  private KeyphraseSourcesSourceId() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface KeyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Key)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 source_id = 2;</code>
     */
    boolean hasSourceId();
    /**
     * <code>optional int32 source_id = 2;</code>
     */
    int getSourceId();
  }
  /**
   * Protobuf type {@code Key}
   */
  public static final class Key extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Key)
      KeyOrBuilder {
    // Use Key.newBuilder() to construct.
    private Key(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Key(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Key defaultInstance;
    public static Key getDefaultInstance() {
      return defaultInstance;
    }

    public Key getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Key(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000001;
              sourceId_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.internal_static_Key_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.internal_static_Key_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Key.class, mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Key.Builder.class);
    }

    public static com.google.protobuf.Parser<Key> PARSER =
        new com.google.protobuf.AbstractParser<Key>() {
      public Key parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Key(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Key> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int SOURCE_ID_FIELD_NUMBER = 2;
    private int sourceId_;
    /**
     * <code>optional int32 source_id = 2;</code>
     */
    public boolean hasSourceId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 source_id = 2;</code>
     */
    public int getSourceId() {
      return sourceId_;
    }

    private void initFields() {
      sourceId_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(2, sourceId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, sourceId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Key parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Key parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Key parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Key parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Key parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Key parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Key parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Key parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Key parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Key parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Key prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Key}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Key)
        mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.KeyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.internal_static_Key_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.internal_static_Key_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Key.class, mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Key.Builder.class);
      }

      // Construct using mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Key.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        sourceId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.internal_static_Key_descriptor;
      }

      public mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Key getDefaultInstanceForType() {
        return mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Key.getDefaultInstance();
      }

      public mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Key build() {
        mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Key result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Key buildPartial() {
        mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Key result = new mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Key(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.sourceId_ = sourceId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Key) {
          return mergeFrom((mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Key)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Key other) {
        if (other == mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Key.getDefaultInstance()) return this;
        if (other.hasSourceId()) {
          setSourceId(other.getSourceId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Key parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Key) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int sourceId_ ;
      /**
       * <code>optional int32 source_id = 2;</code>
       */
      public boolean hasSourceId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 source_id = 2;</code>
       */
      public int getSourceId() {
        return sourceId_;
      }
      /**
       * <code>optional int32 source_id = 2;</code>
       */
      public Builder setSourceId(int value) {
        bitField0_ |= 0x00000001;
        sourceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 source_id = 2;</code>
       */
      public Builder clearSourceId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sourceId_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Key)
    }

    static {
      defaultInstance = new Key(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Key)
  }

  public interface ValuesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Values)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Values.Value values = 1;</code>
     */
    java.util.List<mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values.Value> 
        getValuesList();
    /**
     * <code>repeated .Values.Value values = 1;</code>
     */
    mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values.Value getValues(int index);
    /**
     * <code>repeated .Values.Value values = 1;</code>
     */
    int getValuesCount();
    /**
     * <code>repeated .Values.Value values = 1;</code>
     */
    java.util.List<? extends mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values.ValueOrBuilder> 
        getValuesOrBuilderList();
    /**
     * <code>repeated .Values.Value values = 1;</code>
     */
    mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values.ValueOrBuilder getValuesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Values}
   */
  public static final class Values extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Values)
      ValuesOrBuilder {
    // Use Values.newBuilder() to construct.
    private Values(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Values(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Values defaultInstance;
    public static Values getDefaultInstance() {
      return defaultInstance;
    }

    public Values getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Values(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                values_ = new java.util.ArrayList<mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values.Value>();
                mutable_bitField0_ |= 0x00000001;
              }
              values_.add(input.readMessage(mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values.Value.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          values_ = java.util.Collections.unmodifiableList(values_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.internal_static_Values_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.internal_static_Values_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values.class, mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values.Builder.class);
    }

    public static com.google.protobuf.Parser<Values> PARSER =
        new com.google.protobuf.AbstractParser<Values>() {
      public Values parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Values(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Values> getParserForType() {
      return PARSER;
    }

    public interface ValueOrBuilder extends
        // @@protoc_insertion_point(interface_extends:Values.Value)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>optional string source = 1;</code>
       */
      boolean hasSource();
      /**
       * <code>optional string source = 1;</code>
       */
      java.lang.String getSource();
      /**
       * <code>optional string source = 1;</code>
       */
      com.google.protobuf.ByteString
          getSourceBytes();
    }
    /**
     * Protobuf type {@code Values.Value}
     */
    public static final class Value extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:Values.Value)
        ValueOrBuilder {
      // Use Value.newBuilder() to construct.
      private Value(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Value(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Value defaultInstance;
      public static Value getDefaultInstance() {
        return defaultInstance;
      }

      public Value getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Value(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000001;
                source_ = bs;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.internal_static_Values_Value_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.internal_static_Values_Value_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values.Value.class, mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values.Value.Builder.class);
      }

      public static com.google.protobuf.Parser<Value> PARSER =
          new com.google.protobuf.AbstractParser<Value>() {
        public Value parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Value(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<Value> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      public static final int SOURCE_FIELD_NUMBER = 1;
      private java.lang.Object source_;
      /**
       * <code>optional string source = 1;</code>
       */
      public boolean hasSource() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string source = 1;</code>
       */
      public java.lang.String getSource() {
        java.lang.Object ref = source_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            source_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string source = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSourceBytes() {
        java.lang.Object ref = source_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          source_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private void initFields() {
        source_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getSourceBytes());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getSourceBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values.Value parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values.Value parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values.Value parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values.Value parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values.Value parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values.Value parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values.Value parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values.Value parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values.Value parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values.Value parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values.Value prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code Values.Value}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:Values.Value)
          mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values.ValueOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.internal_static_Values_Value_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.internal_static_Values_Value_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values.Value.class, mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values.Value.Builder.class);
        }

        // Construct using mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values.Value.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          source_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.internal_static_Values_Value_descriptor;
        }

        public mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values.Value getDefaultInstanceForType() {
          return mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values.Value.getDefaultInstance();
        }

        public mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values.Value build() {
          mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values.Value result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values.Value buildPartial() {
          mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values.Value result = new mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values.Value(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.source_ = source_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values.Value) {
            return mergeFrom((mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values.Value)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values.Value other) {
          if (other == mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values.Value.getDefaultInstance()) return this;
          if (other.hasSource()) {
            bitField0_ |= 0x00000001;
            source_ = other.source_;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values.Value parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values.Value) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private java.lang.Object source_ = "";
        /**
         * <code>optional string source = 1;</code>
         */
        public boolean hasSource() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>optional string source = 1;</code>
         */
        public java.lang.String getSource() {
          java.lang.Object ref = source_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              source_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string source = 1;</code>
         */
        public com.google.protobuf.ByteString
            getSourceBytes() {
          java.lang.Object ref = source_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            source_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string source = 1;</code>
         */
        public Builder setSource(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          source_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string source = 1;</code>
         */
        public Builder clearSource() {
          bitField0_ = (bitField0_ & ~0x00000001);
          source_ = getDefaultInstance().getSource();
          onChanged();
          return this;
        }
        /**
         * <code>optional string source = 1;</code>
         */
        public Builder setSourceBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          source_ = value;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:Values.Value)
      }

      static {
        defaultInstance = new Value(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:Values.Value)
    }

    public static final int VALUES_FIELD_NUMBER = 1;
    private java.util.List<mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values.Value> values_;
    /**
     * <code>repeated .Values.Value values = 1;</code>
     */
    public java.util.List<mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values.Value> getValuesList() {
      return values_;
    }
    /**
     * <code>repeated .Values.Value values = 1;</code>
     */
    public java.util.List<? extends mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values.ValueOrBuilder> 
        getValuesOrBuilderList() {
      return values_;
    }
    /**
     * <code>repeated .Values.Value values = 1;</code>
     */
    public int getValuesCount() {
      return values_.size();
    }
    /**
     * <code>repeated .Values.Value values = 1;</code>
     */
    public mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values.Value getValues(int index) {
      return values_.get(index);
    }
    /**
     * <code>repeated .Values.Value values = 1;</code>
     */
    public mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values.ValueOrBuilder getValuesOrBuilder(
        int index) {
      return values_.get(index);
    }

    private void initFields() {
      values_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < values_.size(); i++) {
        output.writeMessage(1, values_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < values_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, values_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Values}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Values)
        mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.ValuesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.internal_static_Values_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.internal_static_Values_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values.class, mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values.Builder.class);
      }

      // Construct using mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getValuesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (valuesBuilder_ == null) {
          values_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          valuesBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.internal_static_Values_descriptor;
      }

      public mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values getDefaultInstanceForType() {
        return mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values.getDefaultInstance();
      }

      public mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values build() {
        mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values buildPartial() {
        mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values result = new mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values(this);
        int from_bitField0_ = bitField0_;
        if (valuesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            values_ = java.util.Collections.unmodifiableList(values_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.values_ = values_;
        } else {
          result.values_ = valuesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values) {
          return mergeFrom((mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values other) {
        if (other == mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values.getDefaultInstance()) return this;
        if (valuesBuilder_ == null) {
          if (!other.values_.isEmpty()) {
            if (values_.isEmpty()) {
              values_ = other.values_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureValuesIsMutable();
              values_.addAll(other.values_);
            }
            onChanged();
          }
        } else {
          if (!other.values_.isEmpty()) {
            if (valuesBuilder_.isEmpty()) {
              valuesBuilder_.dispose();
              valuesBuilder_ = null;
              values_ = other.values_;
              bitField0_ = (bitField0_ & ~0x00000001);
              valuesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getValuesFieldBuilder() : null;
            } else {
              valuesBuilder_.addAllMessages(other.values_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values.Value> values_ =
        java.util.Collections.emptyList();
      private void ensureValuesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          values_ = new java.util.ArrayList<mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values.Value>(values_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values.Value, mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values.Value.Builder, mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values.ValueOrBuilder> valuesBuilder_;

      /**
       * <code>repeated .Values.Value values = 1;</code>
       */
      public java.util.List<mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values.Value> getValuesList() {
        if (valuesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(values_);
        } else {
          return valuesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Values.Value values = 1;</code>
       */
      public int getValuesCount() {
        if (valuesBuilder_ == null) {
          return values_.size();
        } else {
          return valuesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Values.Value values = 1;</code>
       */
      public mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values.Value getValues(int index) {
        if (valuesBuilder_ == null) {
          return values_.get(index);
        } else {
          return valuesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Values.Value values = 1;</code>
       */
      public Builder setValues(
          int index, mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values.Value value) {
        if (valuesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureValuesIsMutable();
          values_.set(index, value);
          onChanged();
        } else {
          valuesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Values.Value values = 1;</code>
       */
      public Builder setValues(
          int index, mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values.Value.Builder builderForValue) {
        if (valuesBuilder_ == null) {
          ensureValuesIsMutable();
          values_.set(index, builderForValue.build());
          onChanged();
        } else {
          valuesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Values.Value values = 1;</code>
       */
      public Builder addValues(mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values.Value value) {
        if (valuesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureValuesIsMutable();
          values_.add(value);
          onChanged();
        } else {
          valuesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Values.Value values = 1;</code>
       */
      public Builder addValues(
          int index, mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values.Value value) {
        if (valuesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureValuesIsMutable();
          values_.add(index, value);
          onChanged();
        } else {
          valuesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Values.Value values = 1;</code>
       */
      public Builder addValues(
          mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values.Value.Builder builderForValue) {
        if (valuesBuilder_ == null) {
          ensureValuesIsMutable();
          values_.add(builderForValue.build());
          onChanged();
        } else {
          valuesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Values.Value values = 1;</code>
       */
      public Builder addValues(
          int index, mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values.Value.Builder builderForValue) {
        if (valuesBuilder_ == null) {
          ensureValuesIsMutable();
          values_.add(index, builderForValue.build());
          onChanged();
        } else {
          valuesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Values.Value values = 1;</code>
       */
      public Builder addAllValues(
          java.lang.Iterable<? extends mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values.Value> values) {
        if (valuesBuilder_ == null) {
          ensureValuesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, values_);
          onChanged();
        } else {
          valuesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Values.Value values = 1;</code>
       */
      public Builder clearValues() {
        if (valuesBuilder_ == null) {
          values_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          valuesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Values.Value values = 1;</code>
       */
      public Builder removeValues(int index) {
        if (valuesBuilder_ == null) {
          ensureValuesIsMutable();
          values_.remove(index);
          onChanged();
        } else {
          valuesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Values.Value values = 1;</code>
       */
      public mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values.Value.Builder getValuesBuilder(
          int index) {
        return getValuesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Values.Value values = 1;</code>
       */
      public mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values.ValueOrBuilder getValuesOrBuilder(
          int index) {
        if (valuesBuilder_ == null) {
          return values_.get(index);  } else {
          return valuesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Values.Value values = 1;</code>
       */
      public java.util.List<? extends mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values.ValueOrBuilder> 
           getValuesOrBuilderList() {
        if (valuesBuilder_ != null) {
          return valuesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(values_);
        }
      }
      /**
       * <code>repeated .Values.Value values = 1;</code>
       */
      public mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values.Value.Builder addValuesBuilder() {
        return getValuesFieldBuilder().addBuilder(
            mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values.Value.getDefaultInstance());
      }
      /**
       * <code>repeated .Values.Value values = 1;</code>
       */
      public mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values.Value.Builder addValuesBuilder(
          int index) {
        return getValuesFieldBuilder().addBuilder(
            index, mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values.Value.getDefaultInstance());
      }
      /**
       * <code>repeated .Values.Value values = 1;</code>
       */
      public java.util.List<mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values.Value.Builder> 
           getValuesBuilderList() {
        return getValuesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values.Value, mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values.Value.Builder, mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values.ValueOrBuilder> 
          getValuesFieldBuilder() {
        if (valuesBuilder_ == null) {
          valuesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values.Value, mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values.Value.Builder, mpi.aida.access.compiledprotos.KeyphraseSourcesSourceId.Values.ValueOrBuilder>(
                  values_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          values_ = null;
        }
        return valuesBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:Values)
    }

    static {
      defaultInstance = new Values(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Values)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Key_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Key_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Values_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Values_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Values_Value_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Values_Value_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!keyphrase_sources-source_id.proto\"\030\n\003K" +
      "ey\022\021\n\tsource_id\030\002 \001(\005\"@\n\006Values\022\035\n\006value" +
      "s\030\001 \003(\0132\r.Values.Value\032\027\n\005Value\022\016\n\006sourc" +
      "e\030\001 \001(\tB \n\036mpi.aida.access.compiledproto" +
      "s"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Key_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Key_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Key_descriptor,
        new java.lang.String[] { "SourceId", });
    internal_static_Values_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Values_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Values_descriptor,
        new java.lang.String[] { "Values", });
    internal_static_Values_Value_descriptor =
      internal_static_Values_descriptor.getNestedTypes().get(0);
    internal_static_Values_Value_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Values_Value_descriptor,
        new java.lang.String[] { "Source", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
